### ISSUE TITLE
Add 5V in DIN-7 pin 4

### ISSUE THREAD

**Issue by bwack** [tebl/C64-Power-Saver#1]
Hi. I saw your post on lemon64. Just a heads up with my experience with selling savers. You should add 5V on DIN-7 pin 4. Less returns from people who have power supplies with 5V pin on the other side of the GND pin.

**Comment by tebl** [comment]
I have adjusted the PCB as well as added a notice for people looking for a solution for PCBs already built. I have only built a handful of these myself, I'm not on lemon64 myself so thank you for bringing this to my attention :-)

**Comment by bwack** [comment]
Got a thank-you message from the guy on lemon64, and I was surprised his name was not tebl hehe.
